baseURL = "https://krishnakumar4a4.github.io"
languageCode = "en-us"
title = "Krishna Kumar T"
theme = "chunky"
paginate = 2
enableInlineShortcodes = true
DefaultContentLanguage = "en"
showReadingTime = true
footnoteReturnLinkContents = "^"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "Tweets"
    name = "Tweets"
    url = "/tweets/"
    weight = 6
  [[menu.main]]
    identifier = "LinkedIn"
    name = "LinkedIn"
    url = "/linkedin/"
    weight = 7
  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"
    weight = 9
  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "pictures"
    name = "Pictures"
    url = "/pictures/"
    weight = 4
  [[menu.main]]
    identifier = "bookmarks"
    name = "Bookmarks"
    url = "/bookmarks/"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params.giscus]
repo = "krishnakumar4a4/krishnakumar4a4.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkxMDA3OTMxMTU="
category = "Blog Comments"
categoryID = "DIC_kwDOBgH7G84CUoxF"
mapping = "title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "light_high_contrast"
lang = "en"
loading = "lazy"

[params]
  author = "Krishna Kumar Thokala"
  description = "I Experiment. I Build."
  homepageImage = ""
  share = true
  showLanguageSwitcher = false
  disqusShortname = "krishnakumart"
  mainSections = ["post"]
  

  [params.social]
    rss = true
    email = "krishna.thokala2010@gmail.com"
    twitter = "https://twitter.com/KrishnaKumarT36"
    linkedin = "https://www.linkedin.com/in/krishnakumarthokala/"
    github = "https://github.com/krishnakumar4a4"
    medium = "https://krishnakumart.medium.com/"
    reddit = "https://reddit.com/u/krishnakumart"
    mastodon = "https://fsmi.social/krishnakumart"
    keybase = "https://keybase.io/krishnakumart"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
